# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addr', models.TextField()),
                ('modelNo', models.CharField(max_length=50)),
                ('registration', models.CharField(max_length=50)),
                ('attendee', models.CharField(max_length=50)),
                ('serviceCategory', models.CharField(max_length=50)),
                ('spares', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
