# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170425_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='lubes',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
