# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_lubes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='spares',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
